---
- name: add gpg key
  apt_key:
    url: "https://repos.influxdata.com/influxdb.key"
    state: present
  tags:
  - telegraf

- name: add repository
  apt_repository:
    repo='deb https://repos.influxdata.com/debian jessie stable'
    state=present
  register: telegraf_repo_added
  tags:
  - telegraf

- name: apt update cache
  apt:
    update_cache: yes
  when: telegraf_repo_added.changed
  tags:
  - telegraf

- name: install telegraf
  apt:
    name: telegraf
    state: present
  tags:
  - telegraf

- name: setup telegraf configuration
  template:
    src: telegraf.conf.j2
    dest: "/etc/telegraf/telegraf.conf"
    force: yes
    backup: yes
    owner: telegraf
    group: telegraf
    mode: 0744
  notify:
  - "restart telegraf"
  tags:
  - telegraf
